---
- name: Converge
  hosts: all
  gather_facts: true

  tasks:
    - name: Set variables for molecule
      set_fact:
        firewall_enabled_at_boot: true
        firewall_enable_ipv6: false  # Added to prevent test failures in CI.
        swap_file_create: false  # Added to prevent test failures in CI.
        sysctl_set: false  # Added to prevent test failures in CI.
        nameservers: ["8.8.8.8", "9.9.9.9"]
        with_haproxy_load_balancing: true
        cacheable: true

    - name: Prepare | Clean yum cache
      command: yum clean all
      when:
        - ansible_os_family == "RedHat"
        - ansible_distribution_major_version == '7'

    - name: Prepare | Clean dnf cache
      command: dnf clean all
      when:
        - ansible_os_family == "RedHat"
        - ansible_distribution_major_version is version('8', '>=')

- import_playbook: ../../deploy_pgcluster.yml

...
